### ISSUE TITLE
Debuff Timer for Hunter Freezing Trap incorrect

### ISSUE THREAD

**Issue by s1lver1us** [shagu/ShaguTweaks#12]
Freezing Trap lasts 10 seconds without Clever Traps Talent, however Debuff Timer shows 20 seconds instead
![WoWScrnShot_050422_001734](https://user-images.githubusercontent.com/99420301/166495801-eddf43a7-4e85-4375-a859-cd26205af618.jpg)
.

Thanks for this amazing addon:)

**Comment by shagu** [comment]
If no rank could be found in the combat log or in recent actions, it will always assume the highest rank (in this case Rank 3), which has 20 seconds. It's all based on guessing and since the majority of people expect the addon to work flawless in end-game, i decided to use the highest rank as default and not the lowest.

**Comment by s1lver1us** [comment]
Ahh okok thanks again!
