### ISSUE TITLE
Feature request: vanilla default nameplate overlap

### ISSUE THREAD

**Issue by brndd** [shagu/ShaguTweaks#18]
Not sure this is something that can be done, but if it's possible to make the default nameplates overlap like you've done with ShaguPlates then that would be a great feature to add.

I did a quick test locally to set the nameplate size to 1x1 px but it completely messed up the layout, so I understand if it's not possible.

**Comment by WuVenus** [comment]
Did you do it?

**Comment by liaochaofeng** [comment]
The other functions are already perfect, but currently the default nameplate of Vanilla overlaps. I hope it can be implemented as soon as possible.

**Comment by WuVenus** [comment]
The other functions are already perfect, but currently the default nameplate of Vanilla overlaps. I hope it can be implemented as soon as possible.

**Comment by shagu** [comment]
It's not possible without manually rebuilding the the entire nameplate exactly, because changing the parent of it alone, will break nearly every texture and sub-frame of it. It's nothing I will do, especially since there is no source of the original nameplate code to lookup things to make a proper clone.
