### ISSUE TITLE
[TBC][AddOn conflict][Module] Square Minimap

### ISSUE THREAD

**Issue by Sattva-108** [shagu/ShaguTweaks#36]
## Description
**Square minimap** module is loading the mask no matter if you have setting **ON** or **OFF**.
Here is mask code in `minimap-square.lua` - `Minimap:SetMaskTexture("Textures\\MinimapMask")`
Enabling square minimap doesn't really solve issue because then minimap looks ugly. (see screenshot below)

## How to reproduce
**Steps:**

1. Install **pfUI-tbc** or **ElvUI**
2. See if you minimap is looking fine.

## Screenshot

**How it looks in pfUI and ElvUI without square minimap option**

![WoW_v5LUPnXFgN](https://user-images.githubusercontent.com/74269253/231601106-cc7e3392-74a5-4d73-9dc2-5fe7f2c6bf03.png)

**How it looks in pfUI with square minimap option**

![WoW_so4PmPBVb8](https://user-images.githubusercontent.com/74269253/231600637-9f005001-626a-4bf2-b49a-77fc0e56b49f.png)

**Comment by Sattva-108** [comment]
Completely disabling the code i mentioned in report is fixing the issue. 
I think it was made so that after disabling square minimap no need to relog to fix square minimap mask?

**Comment by shagu** [comment]
The problem here is that the game does not re-initialize the :SetMinimapMask on `ReloadUI()`. Which means that once it was enabled, it will look like this after you disable it again:

![Screenshot from 2023-04-13 10-00-32](https://user-images.githubusercontent.com/11586807/231693937-863781cb-f104-4556-86c8-6896842387ef.png)

I'll think about another solution.

**Comment by shagu** [comment]
Fixed by https://github.com/shagu/ShaguTweaks/commit/d3b4b5321aa18f4710009876c09b58b8cb9e5bbc
